### ISSUE TITLE
Can't Load any Plugin on BungeeCord Waterfall

### ISSUE THREAD

**Issue by PbtMaster** [FrankHeijden/ServerUtils#14]
When i try to load any Plugin, this Error Happens (i Put $Plugin on the Name of the Plugin, the name is not that):

[02:04:02 WARN]: Error loading plugin $Plugin
net.frankheijden.serverutils.dependencies.minecraftreflection.exceptions.MinecraftReflectionException: Constructor 'new net.md_5.bungee.api.plugin.PluginClassloader(net.md_5.bungee.api.ProxyServer, net.md_5.bungee.api.plugin.PluginDescription, java.net.URL[])' not found!
	at net.frankheijden.serverutils.dependencies.minecraftreflection.Reflection.getConstructor(Reflection.java:126) ~[?:?]
	at net.frankheijden.serverutils.dependencies.minecraftreflection.Reflection.getAccessibleConstructor(Reflection.java:114) ~[?:?]
	at net.frankheijden.serverutils.dependencies.minecraftreflection.Reflection.lambda$newInstance$1(Reflection.java:62) ~[?:?]
	at net.frankheijden.serverutils.dependencies.minecraftreflection.cache.ReflectionCacheTree.computeIfAbsent(ReflectionCacheTree.java:30) ~[?:?]
	at net.frankheijden.serverutils.dependencies.minecraftreflection.Reflection.newInstance(Reflection.java:62) ~[?:?]
	at net.frankheijden.serverutils.bungee.reflection.RPluginClassLoader.newInstance(RPluginClassLoader.java:20) ~[?:?]
	at net.frankheijden.serverutils.bungee.managers.BungeePluginManager.loadPlugin(BungeePluginManager.java:86) ~[?:?]
	at net.frankheijden.serverutils.bungee.managers.BungeePluginManager.loadPlugin(BungeePluginManager.java:71) ~[?:?]
	at net.frankheijden.serverutils.bungee.commands.CommandServerUtils.onLoadPlugin(CommandServerUtils.java:104) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at net.frankheijden.serverutils.bungee.dependencies.acf.RegisteredCommand.invoke(RegisteredCommand.java:152) ~[?:?]
	at net.frankheijden.serverutils.bungee.dependencies.acf.BaseCommand.executeCommand(BaseCommand.java:577) ~[?:?]
	at net.frankheijden.serverutils.bungee.dependencies.acf.BaseCommand.execute(BaseCommand.java:513) ~[?:?]
	at net.frankheijden.serverutils.bungee.dependencies.acf.RootCommand.execute(RootCommand.java:99) ~[?:?]
	at net.frankheijden.serverutils.bungee.dependencies.acf.BungeeRootCommand.execute(BungeeRootCommand.java:83) ~[?:?]
	at net.md_5.bungee.api.plugin.PluginManager.dispatchCommand(PluginManager.java:212) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:8dfe4d2:412]
	at net.md_5.bungee.api.plugin.PluginManager.dispatchCommand(PluginManager.java:163) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:8dfe4d2:412]
	at io.github.waterfallmc.waterfall.console.WaterfallConsole.runCommand(WaterfallConsole.java:30) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:8dfe4d2:412]
	at net.minecrell.terminalconsole.SimpleTerminalConsole.processInput(SimpleTerminalConsole.java:87) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:8dfe4d2:412]
	at net.minecrell.terminalconsole.SimpleTerminalConsole.readCommands(SimpleTerminalConsole.java:168) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:8dfe4d2:412]
	at net.minecrell.terminalconsole.SimpleTerminalConsole.start(SimpleTerminalConsole.java:141) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:8dfe4d2:412]
	at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:80) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:8dfe4d2:412]
	at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:8dfe4d2:412]
Caused by: java.lang.NoSuchMethodException: net.md_5.bungee.api.plugin.PluginClassloader.<init>(net.md_5.bungee.api.ProxyServer, net.md_5.bungee.api.plugin.PluginDescription, [Ljava.net.URL;)
	at java.lang.Class.getConstructor0(Class.java:3349) ~[?:?]
	at java.lang.Class.getDeclaredConstructor(Class.java:2553) ~[?:?]
	at net.frankheijden.serverutils.dependencies.minecraftreflection.Reflection.getConstructor(Reflection.java:124) ~[?:?]
	... 25 more
[02:04:02 INFO]: An error occurred while loading $Plugin, please check the console!

 Steps to Reproduce -->
 
   1- Download Waterfall Build #412 from Papermc
   2- Install ServerUtils v2.5.2
   3- Try to load or reload any Plugin from BungeeCord

**Comment by FrankHeijden** [comment]
Thanks for reporting, ill look into it this week :)
