### ISSUE TITLE
ConcurrentModificationException at Commands#fillUsableCommands

### ISSUE THREAD

**Issue by SrBedrock** [FrankHeijden/ServerUtils#53]
Error when using `/su reloadplugin <plugin>`

```
[18:35:46 ERROR]: Caught previously unhandled exception :
[18:35:46 ERROR]: Paper Async Task Handler Thread - 201
java.util.ConcurrentModificationException: null
        at java.util.TreeMap$PrivateEntryIterator.nextEntry(TreeMap.java:1486) ~[?:?]
        at java.util.TreeMap$ValueIterator.next(TreeMap.java:1531) ~[?:?]
        at net.minecraft.commands.Commands.fillUsableCommands(Commands.java:414) ~[?:?]
        at net.minecraft.commands.Commands.sendAsync(Commands.java:380) ~[?:?]
        at net.minecraft.commands.Commands.sendCommands(Commands.java:364) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by FrankHeijden** [comment]
The error is harmless, but it is caused by the treemap backend which Paper asynchronously iterates over; ServerUtils updates this map when managing plugins’ commands. ServerUtils works on the main thread doing so, there’s not much we can do on our end here 😅

**Comment by FrankHeijden** [comment]
It is also been discussed before in the paper discord, and the likelihood of it being changed is low as managing plugins/commands at runtime is generally disregarded upon

**Comment by SrBedrock** [comment]
No problem, thanks!
